#!/bin/sh

lock() {
  swaylock
}

case "$1" in
  lock)
    swayidle \
      timeout 1 'swaymsg "output * dpms off"' \
      resume 'swaymsg "output * dpms on"' &
    swaylock
    kill %%
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    swaylock --daemonize && systemctl suspend
    ;;
  hibernate)
    swaylock --daemonize && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
esac
                                                                                                                                                
exit 0
