return {}
-- return {
--   {
--     "fgheng/winbar.nvim",
--     config = function()
--       require("winbar").setup({
--         show_file_path = true,
--         show_symbols = true,
--
--         colors = {
--           path = "#383838",
--           file_name = "#383838",
--           symbols = "#383838"
--         }
--
--       })
--     end
--   }
-- }
