#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/git/diva ~/git ~/code ~/fun -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $selected_name ]] && [[ -z $selected ]]; then
	exit 0
fi

# if tmux is running, we attach to the desired session, otherwise we just attach to a running
# client
if [[ -n $TMUX ]]; then
	tmux switch-client -t $selected_name
else
	tmux attach-session -t $selected_name
fi
